Email verification
MohamudIssa/IQrah-BE pull request #3
Opened 2021-08-10 19:23 UTC by MohamudIssa

- Restructured the project
- Created necessary code for the express server to connect and send dynamic emails via sendGrid
- Changed models accordingly

2021-08-10 19:40 UTC, michaelkoek commented on models/model.staff.js
> +    default: 'admin',
Why is the default an admin? So if non is filled a person is always an admin? Doesn't sound to save

2021-08-10 19:40 UTC, michaelkoek commented on routes/login.route.js
> +      console.log(error);
Als put here the `res.status(403).json({ message: 'Wrong email or password' });`

2021-08-10 19:45 UTC, MohamudIssa commented on models/model.staff.js
> +    default: 'admin',
He is like the root user that will be inviting teacher on the platform for the school he is running. He has to be admin when he signs up to be able to have the ability to invite others. Some protected routes are only accessible to admins.

2021-08-11 07:04 UTC, michaelkoek commented
Dont forget to point your merges tot the dev branch.
Easiest way is to set the dev branch as a default

2021-08-11 07:21 UTC, michaelkoek requested changes

2021-08-11 07:21 UTC, michaelkoek commented on models/model.class.js
> +
Remove this unnecessary space

2021-08-11 07:21 UTC, michaelkoek commented on models/model.class.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
school what? school name? school place? school id? 
Specify what you mean

2021-08-11 07:21 UTC, michaelkoek commented on models/model.email.js
> +  secretCode: {
Should be `verificationCode`

2021-08-11 07:21 UTC, michaelkoek commented on models/model.email.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
School what?

2021-08-11 07:21 UTC, michaelkoek commented on models/model.notifications.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
School what?

2021-08-11 07:21 UTC, michaelkoek commented on models/model.notifications.js
> +  subject: {
`title` would be a more common and descriptive name

2021-08-11 07:21 UTC, michaelkoek commented on models/model.parent.js
> +  children: [{ type: mongoose.Schema.Types.ObjectId, ref: 'student' }],
children? Don't you mean student?
And if so; what are you storing of the student? Their name? Their parents name? Their Id? 

`student_id` would be better

2021-08-11 07:21 UTC, michaelkoek commented on models/model.staff.js
> +    type: String,
I remember you saying this only has two statuses "verified" and "pending". Set it to a `enum` type then

2021-08-11 07:21 UTC, michaelkoek commented on models/model.student.js
> +  name: {
is this the full name? first name? last name?
Be specific

2021-08-11 07:21 UTC, michaelkoek commented on models/model.student.js
> +  class: {
I wouldn't know what this data field is going to hold.
Class with type string? Is it a description of the class or something? Which grade they are in? 

Give it a descriptive name

2021-08-11 07:21 UTC, michaelkoek commented on models/model.student.js
> +  School: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
`parent` and `school` should be suffixed with `id` (like stated in the comments before)

2021-08-11 07:21 UTC, michaelkoek commented on routes/emailVer.route.js
> +const router = new Router();
As this is not an import this goes after all the imports

2021-08-11 07:21 UTC, michaelkoek commented on routes/emailVer.route.js
> +  console.log(userid, tempuserid);
No console logs should be merged in the dev branch; remove this

2021-08-11 07:21 UTC, michaelkoek commented on routes/emailVer.route.js
> +          return;
Why do you have here a `return`?

2021-08-11 07:21 UTC, michaelkoek commented on routes/login.route.js
> +const router = new Router();
Move to after all the imports

2021-08-11 07:21 UTC, michaelkoek commented on routes/login.route.js
> +    const re =
`re`? that is totally not a descriptive variable name. what does this regex do? Give it a good name

2021-08-11 07:21 UTC, michaelkoek commented on routes/login.route.js
> +  const validateEmail = function validateEmail(inputEmail) {
Your naming here is very redundant 
```javascript
const validateEmail = function validateEmail(inputEmail) {
```

Choose one of these ways to write the function:
```javascript
// named function
function validateEmail() {

// arrow function (value stored in the const)
const validateEmail = () =>

// anonymous function (value stored in the const) 
const validateEmail = function() {
```

2021-08-11 07:21 UTC, michaelkoek commented on routes/signup.route.js
> +      newSchool.save().then((schoolDB) => {
`.then()` block on a new line for better readability

2021-08-11 07:21 UTC, michaelkoek commented on routes/signup.route.js
> +        newUser.save().then((staffDB) => {
`.then()` block on a new line for better readability

2021-08-11 07:21 UTC, michaelkoek commented on routes/signup.route.js
> +    .then((response) =>
Why are you catching here the `response` and then doing nothing with it? Remove it if you're not using it

2021-08-11 07:21 UTC, michaelkoek commented on utilities/sendEmail.js
> +const API_KEY = process.env.SENDGRID_API_KEY;
`API_KEY` is not descriptive for what kind of key is stored here. Name it `sendgrid_key` or something

2021-08-11 08:11 UTC, ZsokaM approved these changes
sorry, will not have time to review. approving so you can keep going.

2021-08-12 08:53 UTC, MohamudIssa commented on models/model.class.js
> +
removed space.

Done!

2021-08-12 08:57 UTC, MohamudIssa commented on models/model.class.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
It's the ID of the school. Added "_id" at the end.

Done!

2021-08-13 13:19 UTC, MohamudIssa commented on models/model.email.js
> +  secretCode: {
changed.

Done!

2021-08-13 13:20 UTC, MohamudIssa commented on models/model.email.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
i reference the id of the object. Changed to school_id. This also goes for other referenced properties.

Done!

2021-08-13 13:21 UTC, MohamudIssa commented on models/model.notifications.js
> +  school: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
changed to school_id.

Done!

2021-08-13 13:25 UTC, MohamudIssa commented on routes/login.route.js
> +  const validateEmail = function validateEmail(inputEmail) {
this is a mistake. I removed the `const validateEmail =`.

Done!

2021-08-13 13:27 UTC, MohamudIssa commented on routes/signup.route.js
> +      newSchool.save().then((schoolDB) => {
Prietter formats it that way. As soon as I save it move it back.

Done!

2021-08-13 13:28 UTC, MohamudIssa commented on routes/signup.route.js
> +        newUser.save().then((staffDB) => {
Prietter formats it that way. As soon as I save it move it back.

Done!

2021-08-13 13:32 UTC, MohamudIssa commented on routes/signup.route.js
> +    .then((response) =>
good point, I have removed it.

Done!

2021-08-13 13:35 UTC, MohamudIssa commented on utilities/sendEmail.js
> +const API_KEY = process.env.SENDGRID_API_KEY;
I agree, I have formated my code to `sgMail.setApiKey(process.env.SENDGRID_API_KEY)`. No point of re-assigning it to another variable.

Done!

2021-08-13 13:35 UTC, MohamudIssa commented on models/model.notifications.js
> +  subject: {
I agree, changed it to `title`.

Done!

2021-08-13 13:38 UTC, MohamudIssa commented on models/model.parent.js
> +  children: [{ type: mongoose.Schema.Types.ObjectId, ref: 'student' }],
I am storing the students in the children array of the parent. 

Changed this to Children _id. 

When I look for children, its easier to understand if I query for the children instead of the students inside of the parent model. Let me know if you agree.

2021-08-13 13:39 UTC, MohamudIssa commented on models/model.staff.js
> +    type: String,
Very good point, added  ` enum: ['pending', 'verified'],` property.

Done!

2021-08-13 13:40 UTC, MohamudIssa commented on models/model.student.js
> +  name: {
Changed the propery to `full_name`.

Done!

2021-08-13 13:48 UTC, MohamudIssa commented on models/model.student.js
> +  class: {
Changed it to `classroom`. I think its slightly better. It's not a location but `groep`. Student will be divided up in classrooms.

Done!

2021-08-13 13:49 UTC, MohamudIssa commented on models/model.student.js
> +  School: { type: mongoose.Schema.Types.ObjectId, ref: 'school' },
Done!

2021-08-13 13:59 UTC, MohamudIssa commented on routes/emailVer.route.js
> +const router = new Router();
can you clarify what you mean?

2021-08-13 13:59 UTC, MohamudIssa commented on routes/emailVer.route.js
> +  console.log(userid, tempuserid);
removed. 

Done!

2021-08-13 14:01 UTC, MohamudIssa commented on routes/emailVer.route.js
> +          return;
not sure.. I dont need it. It's removed.

Done!

2021-08-13 14:02 UTC, MohamudIssa commented on routes/login.route.js
> +const router = new Router();
Moved `const router = new Router();` below all the imports.

Done!

2021-08-13 14:03 UTC, MohamudIssa commented on routes/login.route.js
> +    const re =
heheh, changed it to `regex` 

Done!

2021-08-14 08:42 UTC, michaelkoek commented on models/model.parent.js
> +  children: [{ type: mongoose.Schema.Types.ObjectId, ref: 'student' }],
As the context of your application is regarding a school system I think students is a more suitable name as it's very explicit that it's regarding 'children that are enrolled in the school' aka students. 'children' could also mean children that are not part of the school

2021-08-14 08:46 UTC, michaelkoek commented on routes/emailVer.route.js
> +const router = new Router();
```javascript
const router = new Router();
```
This is not an "import" from a package or file. This `new Router` is an extension of something you're importing.
The convention is that at the top of the file you import/require all the modules and files and afterwards you use or initialise them.



`new Router` is the enrichment of the express reouter you're importing.
Also, notice that you're importing/requiring `express` twice

```javascript
const express = require('express');
const { Router } = require('express');
```
Don't do this

2021-08-16 11:31 UTC, guido-an approved these changes

2021-08-16 14:29 UTC, michaelkoek commented on models/model.email.js
> +    expireAfterSeconds: 1800,
these are milliseconds (ms), not seconds

2021-08-17 05:35 UTC, MohamudIssa commented on models/model.email.js
> +    expireAfterSeconds: 1800,
Done!

2021-08-17 06:14 UTC, MohamudIssa commented on models/model.parent.js
> +  children: [{ type: mongoose.Schema.Types.ObjectId, ref: 'student' }],
I agree, it's changed.

Done!

2021-08-17 06:15 UTC, MohamudIssa commented on routes/emailVer.route.js
> +const router = new Router();
Done!

2021-08-17 12:05 UTC, michaelkoek approved these changes

2021-08-17 14:00 UTC, merged